[tool.poetry]
name = "jwt"
version = "0.1.0"
description = ""
authors = ["Alpha-Potat <luchinin.n@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pyjwt = "^2.8.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
